update=Tue 05 Jun 2018 04:02:49 AM WEST
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/ir
LibName34=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/ADCchain
LibName35=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/hirose
LibName36=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/lm1117
LibName37=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/myconn3
LibName38=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/PJ-102A
LibName39=/home/moinocencio/Setups/Kicad Libraries/KicadPartsMaster/KiCad-Parts-master/xmossupport
LibName40=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/references
LibName41=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/ac-dc
LibName42=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/adc-dac
LibName43=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Altera
LibName44=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/analog_devices
LibName45=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/analog_switches
LibName46=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/atmel
LibName47=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/audio
LibName48=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Battery_Management
LibName49=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/bbd
LibName50=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Bosch
LibName51=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/brooktre
LibName52=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Connector
LibName53=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/contrib
LibName54=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/cypress
LibName55=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/dc-dc
LibName56=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Decawave
LibName57=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/device
LibName58=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/digital-audio
LibName59=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Diode
LibName60=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Display
LibName61=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/driver_gate
LibName62=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/dsp
LibName63=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/DSP_Microchip_DSPIC33
LibName64=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/elec-unifil
LibName65=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/ESD_Protection
LibName66=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Espressif
LibName67=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/FPGA_Actel
LibName68=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/ftdi
LibName69=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/gennum
LibName70=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Graphic
LibName71=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/hc11
LibName72=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/infineon
LibName73=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/intel
LibName74=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/interface
LibName75=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/intersil
LibName76=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Lattice
LibName77=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/LED
LibName78=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/LEM
LibName79=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/linear
LibName80=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Logic_74xgxx
LibName81=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Logic_74xx
LibName82=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Logic_CMOS_4000
LibName83=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Logic_CMOS_IEEE
LibName84=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/logic_programmable
LibName85=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Logic_TTL_IEEE
LibName86=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/maxim
LibName87=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC10
LibName88=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC12
LibName89=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC16
LibName90=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC18
LibName91=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC24
LibName92=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Microchip_PIC32
LibName93=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_NXP_Kinetis
LibName94=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_NXP_LPC
LibName95=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_NXP_S08
LibName96=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Parallax
LibName97=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_ST_STM8
LibName98=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_ST_STM32
LibName99=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/MCU_Texas_MSP430
LibName100=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Mechanical
LibName101=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/memory
LibName102=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/microchip
LibName103=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/microcontrollers
LibName104=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/modules
LibName105=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Motor
LibName106=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/motor_drivers
LibName107=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/motorola
LibName108=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/nordicsemi
LibName109=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/nxp
LibName110=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/onsemi
LibName111=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/opto
LibName112=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Oscillators
LibName113=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/philips
LibName114=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/power
LibName115=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/powerint
LibName116=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Power_Management
LibName117=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/pspice
LibName118=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/regul
LibName119=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Relay
LibName120=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/RF_Bluetooth
LibName121=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/rfcom
LibName122=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/RFSolutions
LibName123=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Sensor_Current
LibName124=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Sensor_Humidity
LibName125=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/sensors
LibName126=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/silabs
LibName127=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/siliconi
LibName128=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/supertex
LibName129=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Switch
LibName130=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/texas
LibName131=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Transformer
LibName132=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Transistor
LibName133=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/triac_thyristor
LibName134=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Valve
LibName135=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/video
LibName136=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/wiznet
LibName137=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Worldsemi
LibName138=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Xicor
LibName139=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx
LibName140=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-artix7
LibName141=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-kintex7
LibName142=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-spartan6
LibName143=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-virtex5
LibName144=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-virtex6
LibName145=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/xilinx-virtex7
LibName146=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/zetex
LibName147=/home/moinocencio/Setups/Kicad Libraries/kicad-library-master/library/Zilog
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=./
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
